/**
 * VeriShield Compact contracts.
 *
 * Source of truth: `src/credential-registry.compact`.
 * Compiled artifacts: `managed/credential-registry/` (generated by
 * `pnpm --filter @verishield/contracts compile`).
 *
 * This module re-exports the generated bindings so the rest of the monorepo
 * can drive the contract through the Midnight runtime without touching the
 * generated files directly.
 */

export {
  Contract,
  ledger,
  pureCircuits,
  ClaimType,
  contractReferenceLocations,
} from '../managed/credential-registry/contract/index.js';

export type {
  Witnesses,
  ImpureCircuits,
  ProvableCircuits,
  PureCircuits,
  Circuits,
  Ledger,
  ContractReferenceLocations,
} from '../managed/credential-registry/contract/index.js';

export const COMPACT_CONTRACT_NAMES = ['credential-registry'] as const;

export type CompactContractName = (typeof COMPACT_CONTRACT_NAMES)[number];

/** Compiler / language / runtime versions this build targets (ledger v8). */
export const COMPACT_VERSIONS = {
  compiler: '0.31.1',
  language: '0.23.0',
  runtime: '0.16.0',
  ledger: 'ledger-8.0.2',
} as const;

/** Name of the only on-chain ledger field a verifier ever reads. */
export const PUBLIC_PROOF_OUTPUT = 'lastProofValid' as const;
